/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rhora.h"

bool_t
xdr_horastat (XDR *xdrs, horastat *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_segactual (XDR *xdrs, segactual *objp)
{
	register int32_t *buf;

	 if (!xdr_horastat (xdrs, &objp->status))
		 return FALSE;
	switch (objp->status) {
	case HORA_OK:
		 if (!xdr_long (xdrs, &objp->segactual_u.segundos))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
